from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from tqdm import tqdm

from src.clip_encoder import ClipEncoder
from src.config import resolve_project_path
from src.milvus_client import insert_embeddings


def index_single_image(row: pd.Series, encoder: ClipEncoder) -> dict[str, Any]:
    """Encode one metadata row into the fields required by Milvus."""
    image_path = resolve_project_path(row["image_path"])
    embedding = encoder.encode_image(image_path).tolist()

    return {
        "image_path": Path(row["image_path"]).as_posix(),
        "caption": str(row.get("caption", "")),
        "embedding": embedding,
    }


def index_images(
    metadata_path: str | Path,
    encoder: ClipEncoder,
    collection,
    batch_size: int = 32,
    max_images: int | None = None,
) -> int:
    """Encode image metadata rows and insert them into Milvus in batches."""
    metadata = pd.read_csv(resolve_project_path(metadata_path))
    if max_images:
        metadata = metadata.head(max_images)

    total_inserted = 0
    image_paths: list[str] = []
    captions: list[str] = []
    embeddings: list[list[float]] = []

    for _, row in tqdm(metadata.iterrows(), total=len(metadata), desc="Indexing images"):
        item = index_single_image(row, encoder)
        image_paths.append(item["image_path"])
        captions.append(item["caption"])
        embeddings.append(item["embedding"])

        if len(image_paths) >= batch_size:
            insert_embeddings(collection, image_paths, captions, embeddings)
            total_inserted += len(image_paths)
            image_paths, captions, embeddings = [], [], []

    if image_paths:
        insert_embeddings(collection, image_paths, captions, embeddings)
        total_inserted += len(image_paths)

    return total_inserted


def load_precomputed_embeddings(embeddings_path: str | Path) -> np.ndarray:
    """Load normalized image embeddings generated by an offline encoder."""
    path = resolve_project_path(embeddings_path)
    if not path.exists():
        raise FileNotFoundError(
            f"Embedding file not found: {path}. "
            "Run the Kaggle offline encoder and place image_embeddings.npy here first."
        )

    embeddings = np.load(path)
    if embeddings.ndim != 2:
        raise ValueError(f"Expected a 2D embedding array, got shape {embeddings.shape}.")

    return embeddings.astype("float32", copy=False)


def index_precomputed_embeddings(
    metadata_path: str | Path,
    embeddings_path: str | Path,
    collection,
    batch_size: int = 256,
    max_images: int | None = None,
) -> int:
    """Insert precomputed image vectors into Milvus in batches."""
    metadata = pd.read_csv(resolve_project_path(metadata_path))
    embeddings = load_precomputed_embeddings(embeddings_path)

    if len(metadata) != len(embeddings):
        raise ValueError(
            "Metadata rows and embedding rows must match: "
            f"{len(metadata)} metadata rows vs {len(embeddings)} embeddings."
        )

    if max_images:
        metadata = metadata.head(max_images)
        embeddings = embeddings[:max_images]

    total_inserted = 0
    for start in tqdm(range(0, len(metadata), batch_size), desc="Loading embeddings into Milvus"):
        end = start + batch_size
        batch_metadata = metadata.iloc[start:end]
        batch_embeddings = embeddings[start:end]

        image_paths = [Path(path).as_posix() for path in batch_metadata["image_path"].tolist()]
        if "caption" in batch_metadata:
            captions = batch_metadata["caption"].fillna("").astype(str).tolist()
        else:
            captions = [""] * len(batch_metadata)

        insert_embeddings(collection, image_paths, captions, batch_embeddings.tolist())
        total_inserted += len(batch_metadata)

    return total_inserted
